name: Definition of Done sample workflow

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [edited]

jobs:
  check-dod:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Check DoDz
        uses: platisd/DoD-checker@master
        with:
          dod_yaml: 'sample_dod.yaml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
